<?xml version="1.0"?>
<package format="3">
  <name>opr_gazebo</name>
  <version>0.0.0</version>
  <description>Gazebo related worlds/models for Open Platform Robot</description>
  <maintainer email="supratmanjoshua@gmail.com">Joshua Supratman</maintainer>
  <license>Apache License, Version 2.0</license>
  <buildtool_depend>catkin</buildtool_depend>
  <export>
    <gazebo_ros gazebo_media_path="${prefix}/worlds"/>
    <gazebo_ros gazebo_media_path="${prefix}/materials"/>
    <gazebo_ros gazebo_model_path="${prefix}/models"/>
  </export>
</package>
