<?xml version="1.0"?>
<package format="3">
  <name>opr_behavior</name>
  <version>0.0.0</version>
  <description>opr_behavior</description>
  <maintainer email="supratmanjoshua@gmail.com">jsupratman13</maintainer>
  <license>Apache License, Version 2.0</license>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>rospy</depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>vision_msgs</exec_depend>
  <export/>
</package>
