joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

head_yaw_controller:
  type: position_controllers/JointPositionController
  publish_rate: 10
  base_frame_id: base_link
  joint: head_yaw_joint

joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - left_shoulder_pitch_joint
    - left_shoulder_roll_joint
    - left_elbow_pitch_joint
    - left_waist_yaw_joint
    - left_waist_roll_joint
    - left_waist_pitch_joint
    - left_knee_pitch_joint
    - left_ankle_pitch_joint
    - left_ankle_roll_joint
    - right_shoulder_pitch_joint
    - right_shoulder_roll_joint
    - right_elbow_pitch_joint
    - right_waist_yaw_joint
    - right_waist_roll_joint
    - right_waist_pitch_joint
    - right_knee_pitch_joint
    - right_ankle_pitch_joint
    - right_ankle_roll_joint
