<?xml version="1.0"?>
<package format="3">
  <name>opr_ros</name>
  <version>0.0.0</version>
  <description>Meta package for Open Platform Robot</description>
  <maintainer email="supratmanjoshua@gmail.com">Joshua Supratman</maintainer>
  <license>Apache License, Version 2.0</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>opr_bringup</exec_depend>
  <exec_depend>opr_description</exec_depend>
  <exec_depend>opr_gazebo</exec_depend>
  <exec_depend>opr_imu</exec_depend>

  <export>
    <metapackage/>
  </export>
</package>
